[package]
name = "potatolang"
version = "0.2.0"  # Matches your VERSION constant
edition = "2021"   # Use the 2021 edition of Rust (or whichever you prefer)
authors = ["Faris Al-Lafi"]  # Add your name or handle!
description = "A custom programming language"